### ISSUE TITLE
Disabled witness should be removed from the Blockchain, and it should be updated on witness voting section 

### ISSUE THREAD

**Issue by rabTAI** [smokenetwork/smoked#24]
![image](https://user-images.githubusercontent.com/1568153/49552361-6491a800-f8b0-11e8-8313-9b42b6c92dad.png)

**Comment by baabeetaa** [comment]
disabled witnesses could not produce blocks and not in active-witnesses. Should not change it unless there is a very good reason.

**Comment by rabTAI** [comment]
Thanks @baabeetaa, so https://smoked.online/ this is where I see all those active-witnesses. Can we update this page with that list>>https://smoke.io/~witnesses, remove disabled one on this top 50.

**Comment by anxiousstoner** [comment]
> Thanks @baabeetaa, so https://smoked.online/ this is where I see all those active-witnesses. Can we update this page with that list>>https://smoke.io/~witnesses, remove disabled one on this top 50.

Then ppl won't know to unvote witnesses.    A better solution is displaying perhaps the top 100 or all the witnesses on the smoke.io witness page
