### ISSUE TITLE
some bugs with the tags i guess

### ISSUE THREAD

**Issue by pranishg** [smokenetwork/smoked#29]
so i have been building a dapp on top of smoke --- 
when ever we try to post something on smoke network through our app it gets broadcasted to the blockchain but not visible in smoke.io 

for example 
https://smoke.io/vidsocial/@pragyan78/my-first-video-

 this post is visible if i directly opened the link 

but if we go to the author's profile its not visible -- not visible in the home page too 
https://smoke.io/@pragyan78

please check this baa

**Comment by anxiousstoner** [comment]
This has nothing to do with smoked.  Please see /webapp.
